name: mutcv
url: http://blog.mutcv.com
description: A blog about algorithm and game
colors: light

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md']
sass:
    style: compressed
