name: mutcv
title: mutcv
url: http://blog.mutcv.com
keywords: Python
description: 吾日三省吾身
colors: mutcv

permalink: /:year/:month/:day/:title/
paginate: 10

g_analytics: "UA-89493312-1"

gems: [jekyll-paginate]
exclude: ['README.md', 'src']
sass:
    style: compressed
