name: mutcv
title: mutcv
url: http://blog.mutcv.com
keywords: Python
description: A blog about Python
colors: dark

permalink: /:year/:month/:day/:title/
paginate: 10

g_analytics: "UA-89493312-1"

gems: [jekyll-paginate]
exclude: ['README.md']
sass:
    style: compressed
